# Step 1: Node.js 18.13-alpine 이미지를 사용하여 빌드 환경을 설정
FROM node:20.15.0-alpine as builder

# 작업 폴더를 만들고 npm 설치
WORKDIR /usr/src/app

# package.json 파일을 작업 폴더로 복사
COPY package.json /usr/src/app/package.json

# 패키지들을 설치
RUN npm install --force

# 소스를 작업 폴더로 복사하고 빌드
COPY . /usr/src/app
RUN npm run build