spring:
  application:
    name: A708
  mail:
    username: cosmosa708@gmail.com
    password: smja mhgo oofr iykx

  datasource:
    url:
    username: produser
    password: prodpass

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

logging:
  level:
    root: warn

jwt:
  secret-key: lGmYbu6wGqW37992AMeifFGoUzlYEQyUSIoc1FCLG6g=

oauth:
  kakao:
    client-id: 5dc1b39c3ec1e01e34200896d28b756f
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
  naver:
    secret: PHuFkNpuoZ
    client-id: 6yuLNhBVLUEs87FgWVLO
    url:
      auth: https://nid.naver.com
      api: https://openapi.naver.com

openvidu:
  url: https://i11a708.p.ssafy.io:8443/
  secret: MY_SECRET
