spring:
  application:
    name: A708
  mail:
    username: ${EMAIL}
    password: ${EMAIL_PASSWORD}

  datasource:
    url: ${DB_URL}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    root: info

jwt:
  secret-key: ${JWT_SECRET_KEY}


oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
  naver:
    secret: ${NAVER_SECRET}
    client-id: ${NAVER_CLIENT_ID}
    url:
      auth: https://nid.naver.com
      api: https://openapi.naver.com

openvidu:
  url: https://i11a708.p.ssafy.io:8443/
  secret: MY_SECRET