spring:
  application:
    name: A708
  mail:
    host: smtp.gmail.com
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
            trust: smtp.gmail.com

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  servlet:
    context-path: /api
  port: '8080'

logging:
  level:
    root: info

jwt:
  access:
    expiration: 3600000
  refresh:
    expiration: 604800000

app:
  expired-time: 5

openvidu:
  url: https://i11a708.p.ssafy.io:8443/
  secret: MY_SECRET
